---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.4
    driver_config:
      network:
      - ["forwarded_port", {guest: 80, host: 8880}]
      - ["forwarded_port", {guest: 81, host: 8881}]

suites:
  - name: default
    run_list:
      - recipe[apache::default]
    attributes:
      motd:
        company: For Profit Online University
